import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Clock3, Video, ClipboardCheck } from 'lucide-react';
import Seo from '../../components/ui/Seo.jsx';
import SectionCard from '../../components/portal/SectionCard.jsx';
import { listPublishedSessions } from '../../lib/supabase/learning.js';
import { LoadingState, ErrorState, EmptyState } from '../../components/portal/PortalStates.jsx';

export default function Calendar() {
  const [state, setState] = useState({ loading: true, error: null, sessions: [] });
  useEffect(() => { listPublishedSessions().then((sessions) => setState({ loading: false, error: null, sessions })).catch((err) => setState({ loading: false, error: err.message, sessions: [] })); }, []);
  const grouped = useMemo(() => state.sessions.reduce((acc, item) => { const key = new Date(item.starts_at).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }); (acc[key] ||= []).push(item); return acc; }, {}), [state.sessions]);
  return <><Seo title="Learning Calendar" description="Your learning calendar." path="/learn/calendar" /><div><p className="font-body text-xs font-semibold uppercase tracking-wider text-gold-600">Schedule</p><h1 className="mt-1 font-display text-3xl font-bold text-navy-900">Learning Calendar</h1><p className="mt-2 font-body text-sm text-navy-500">A single place for live sessions and, as assessment scheduling is connected, upcoming deadlines and assessments.</p></div><div className="mt-6">{state.loading && <LoadingState />}{state.error && <ErrorState message={state.error} />}{!state.loading && !state.error && !state.sessions.length && <EmptyState icon={CalendarDays} title="Your calendar is clear" message="Published learning sessions will be grouped here by date." />}{Object.entries(grouped).map(([day, items]) => <section key={day} className="mb-7"><h2 className="mb-3 font-display text-lg font-bold text-navy-900">{day}</h2><div className="space-y-3">{items.map((item) => <SectionCard key={item.id} className="p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-body text-xs font-bold uppercase tracking-wide text-gold-600">{item.session_type?.replaceAll('_', ' ')}</p><h3 className="mt-1 font-display text-base font-bold text-navy-900">{item.title}</h3><p className="mt-1 font-body text-sm text-navy-500">{item.lms_courses?.title || 'Course session'}</p></div><div className="flex flex-wrap gap-3 font-body text-xs font-semibold text-navy-500"><span><Clock3 className="mr-1 inline" size={13}/>{new Date(item.starts_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span><span>{item.session_type === 'assessment' ? <ClipboardCheck className="mr-1 inline" size={13}/> : <Video className="mr-1 inline" size={13}/>} Scheduled</span></div></div></SectionCard>)}</div></section>)}</div></>;
}
