import { useEffect, useState } from 'react';
import { CalendarDays, Clock3, Video, MapPin, ExternalLink, CheckCircle2, PlayCircle } from 'lucide-react';
import Seo from '../../components/ui/Seo.jsx';
import SectionCard from '../../components/portal/SectionCard.jsx';
import { listPublishedSessions } from '../../lib/supabase/learning.js';
import { checkInSession } from '../../lib/supabase/platform.js';
import { LoadingState, ErrorState, EmptyState } from '../../components/portal/PortalStates.jsx';

export default function Sessions() {
  const [state, setState] = useState({ loading: true, error: null, sessions: [] });
  const [checked, setChecked] = useState(new Set());
  const [busy, setBusy] = useState('');
  async function load() { try { const sessions = await listPublishedSessions(); setState({ loading: false, error: null, sessions }); } catch (err) { setState({ loading: false, error: err.message, sessions: [] }); } }
  useEffect(() => { load(); }, []);
  async function checkIn(id) { try { setBusy(id); await checkInSession(id); setChecked((p) => new Set([...p, id])); } catch (e) { setState((p) => ({ ...p, error: e.message })); } finally { setBusy(''); } }
  return <><Seo title="Live Sessions" description="Your scheduled learning sessions." path="/learn/sessions" /><div><p className="eyebrow">Learning schedule</p><h1 className="page-title">Live Sessions</h1><p className="page-copy">Join scheduled lectures, tutorials, practical demonstrations, workshops and office hours. Attendance can be recorded from this page.</p></div><div className="mt-6">{state.loading && <LoadingState />}{state.error && <ErrorState message={state.error} />}{!state.loading && !state.error && !state.sessions.length && <EmptyState icon={Video} title="No sessions published yet" message="When an instructor publishes a session for one of your courses, it will appear here." />}{!state.loading && !state.error && state.sessions.length > 0 && <div className="grid gap-4 md:grid-cols-2">{state.sessions.map((s) => { const start = new Date(s.starts_at); const end = new Date(s.ends_at); const live = Date.now() >= start.getTime() && Date.now() <= end.getTime(); return <SectionCard key={s.id} className="p-6"><div className="flex items-start justify-between gap-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-gold-500/10 text-gold-700"><Video size={19}/></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${live?'bg-emerald-50 text-emerald-700':'bg-navy-50 text-navy-600'}`}>{live?'Live now':s.session_type?.replaceAll('_',' ')}</span></div><h2 className="mt-5 font-display text-lg font-bold capitalize text-navy-900">{s.title}</h2><p className="mt-1 font-body text-sm text-navy-500">{s.lms_courses?.title || 'Course session'}</p>{s.description&&<p className="mt-3 font-body text-sm leading-6 text-navy-600">{s.description}</p>}<div className="mt-5 space-y-2 font-body text-xs font-semibold text-navy-500"><p><CalendarDays className="mr-2 inline" size={14}/>{start.toLocaleString()}</p><p><Clock3 className="mr-2 inline" size={14}/>Until {end.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</p>{(s.location||s.meeting_url)&&<p><MapPin className="mr-2 inline" size={14}/>{s.location||'Online'}</p>}</div><div className="mt-5 flex flex-wrap gap-2">{s.meeting_url&&<a href={s.meeting_url} target="_blank" rel="noreferrer" className="btn-gold inline-flex items-center gap-2 text-sm">Join session <ExternalLink size={14}/></a>}<button onClick={()=>checkIn(s.id)} disabled={busy===s.id||checked.has(s.id)} className="btn-outline inline-flex items-center gap-2 text-sm">{checked.has(s.id)?<><CheckCircle2 size={14}/>Attendance recorded</>:<><CheckCircle2 size={14}/>{busy===s.id?'Recording…':'Check in'}</>}</button>{s.recording_url&&<a href={s.recording_url} target="_blank" rel="noreferrer" className="btn-outline inline-flex items-center gap-2 text-sm"><PlayCircle size={14}/>Recording</a>}</div></SectionCard>})}</div>}</div></>;
}
